---
title: "Thread Summary"
author: "JMR"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
params:
  raw_qual_coded_data: ""
  coded_threads: ""
  all_unfiltered_coded_threads: ""
  users_to_analyze: ""
---

```{r setup, include=FALSE, eval = TRUE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE)

library(rtweet)
library(ggraph)
library(igraph)
library(tidygraph)
library(cowplot)
library(readxl)
library(irr)
library(multcomp)
library(brms)
library(tidyverse)

library(conflicted)

conflict_prefer("filter", "dplyr")
conflict_prefer("gather", "tidyr")
conflict_prefer("select", "dplyr")
```


```{r}
d <- raw_qual_coded_data %>% slice(201:300)
d <- d %>% 
  dplyr::select(JWR = Code, JMR = Notes)

irr::kappa2(d[1:50, ])
irr::agree(d[1:50, ])

irr::kappa2(d[51:100, ])
irr::agree(d[51:100, ])
```

```{r}
coded_threads %>% janitor::tabyl(code)
```

```{r}
coded_threads %>% 
  count(ID) %>% 
  filter(is.na(ID)) 

qa_rows <- coded_threads %>% 
  filter(is.na(ID)) %>% 
  nrow()
```

```{r}
coded_threads %>% count(ID) %>% filter(str_detect(ID, "uc"))
uc_rows <- coded_threads %>% filter(str_detect(ID, "uc")) %>% nrow()
```

```{r}
qa_rows
uc_rows
qa_rows - uc_rows
qa_rows + uc_rows
```

```{r}
u <- u %>% 
  select(-code)

d <- d %>% mutate(screen_name = tolower(screen_name))
dd <- d %>% 
  left_join(u) %>% 
  left_join(i)

dd <- dd %>% 
  mutate(group = if_else(is.na(group), "Unclear", group))

dd <- dd %>% 
  mutate(group = if_else(group == "Unclear", "Other", group))

dd <- dd %>% 
  filter(code != "RT")
```

# Freqs

```{r}
dd %>% 
  janitor::tabyl(code)
```

```{r}
dd %>% 
  filter(!(str_detect(ID, "uc") | str_detect(ID, "qa"))) %>% 
  janitor::tabyl(code)
```

# N singletons

```{r}
dd %>% 
  filter(str_detect(ID, "uc") | str_detect(ID, "qa")) %>% 
  count(str_detect(ID, "uc"))
```
