---
title: "Thread Summary"
author: "JMR"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
params:
  raw_qual_coded_data: ""
  coded_threads: ""
  all_unfiltered_coded_threads: ""
  users_to_analyze: ""
  influence: ""
---

```{r setup, include=FALSE, eval = TRUE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE)

raw_qual_coded_data <- params$raw_qual_coded_data
coded_threads <- params$coded_threads
```


```{r}
d <- raw_qual_coded_data %>% slice(201:300)
d <- d %>% 
  dplyr::select(JWR = Code, JMR = Notes) %>% 
  mutate(JWR = if_else(is.na(JWR), "SB", JWR))

irr::kappa2(d[1:50, ])
irr::agree(d[1:50, ])

irr::kappa2(d[51:100, ])
irr::agree(d[51:100, ])
```

```{r}
coded_threads %>% janitor::tabyl(code)
```

```{r}
coded_threads %>% count(ID) %>% filter(is.na(ID)) 
qa_rows <- coded_threads %>% filter(is.na(ID)) %>% nrow()
```

```{r}
coded_threads %>% count(ID) %>% filter(str_detect(ID, "uc"))
uc_rows <- coded_threads %>% filter(str_detect(ID, "uc")) %>% nrow()
```

```{r}
qa_rows
uc_rows
qa_rows - uc_rows
qa_rows + uc_rows
```

```{r}
d <- params$all_unfiltered_coded_threads
u <- params$users_to_analyze
influence <- params$influence
```

```{r}
# 11127 tweets in threads; 8,384 unique tweets

u <- u %>% 
  select(-code)

i <- influence %>% 
  select(screen_name, adoption_tri)

d <- d %>% mutate(screen_name = tolower(screen_name))
dd <- d %>% 
  left_join(u) %>% 
  left_join(i)

dd <- dd %>% 
  mutate(group = if_else(is.na(group), "Unclear", group))

dd <- dd %>% 
  mutate(group = if_else(group == "Unclear", "Other", group))

dd <- dd %>% 
  filter(code != "RT")
```

# Checking the data

```{r, eval = FALSE}
sno <- dd %>% 
  #filter(!(str_detect(ID, "uc") | str_detect(ID, "qa"))) %>% 
  pull(screen_name) %>% 
  unique()

i$screen_name %in% sno
```

# Freqs

```{r}
dd %>% 
  janitor::tabyl(code)
```

```{r}
dd %>% 
  filter(!(str_detect(ID, "uc") | str_detect(ID, "qa"))) %>% 
  janitor::tabyl(code)
```

# N singletons

```{r}
dd %>% 
  filter(str_detect(ID, "uc") | str_detect(ID, "qa")) %>% 
  count(str_detect(ID, "uc"))
```

# N individuals participated

```{r}
# mean
n_group_mean <- dd %>% 
  count(ID, group, code) %>% 
  spread(group, n, fill = 0) %>% 
  dplyr::select(ID:Teacher) %>% 
  gather(key, val, -ID, -code) %>% 
  group_by(code, key) %>% 
  summarize(mean_val = mean(val)) %>% 
  spread(key, mean_val) %>% 
  ungroup() %>% 
  arrange(desc(Administrator)) %>% 
  dplyr::select(Code = code, Teacher, Administrator, Researcher, Organization, Other) %>% 
  mutate_if(is.double, round, 2)

# sd
n_group_sd <- dd %>% 
  count(ID, group, code) %>% 
  spread(group, n, fill = 0) %>% 
  dplyr::select(ID:Teacher) %>% 
  gather(key, val, -ID, -code) %>% 
  group_by(code, key) %>% 
  summarize(sd_val = sd(val)) %>% 
  spread(key, sd_val) %>% 
  ungroup() %>% 
  dplyr::select(Code = code, Teacher, Administrator, Researcher, Organization, Other) %>% 
  mutate_if(is.double, round, 2) %>% 
  set_names(c("Code", str_c("sd_", names(.[2:6]))))

n_group_mean
n_group_sd
```

# N adoption statuses

```{r}
dd <- dd %>% 
  mutate(adoption_tri = as.character(adoption_tri)) %>% 
  mutate(adoption_tri_c = if_else(is.na(adoption_tri), "missing", adoption_tri))

# mean
n_adoption_mean <- dd %>% 
  filter(!(str_detect(ID, "uc") | str_detect(ID, "qa"))) %>% 
  count(ID, adoption_tri_c, code) %>% 
  spread(adoption_tri_c, n, fill = 0) %>% 
  dplyr::select(ID:not) %>% 
  gather(key, val, -ID, -code) %>% 
  group_by(code, key) %>% 
  summarize(mean_val = mean(val)) %>% 
  spread(key, mean_val) %>% 
  ungroup() %>% 
  mutate_if(is.double, round, 2)

# sd
n_adoption_sd <- dd %>% 
  filter(!(str_detect(ID, "uc") | str_detect(ID, "qa"))) %>% 
  count(ID, adoption_tri_c, code) %>% 
  spread(adoption_tri_c, n, fill = 0) %>% 
  dplyr::select(ID:not) %>% 
  gather(key, val, -ID, -code) %>% 
  group_by(code, key) %>% 
  summarize(sd_val = sd(val)) %>% 
  spread(key, sd_val) %>% 
  ungroup() %>% 
  mutate_if(is.double, round, 2) %>% 
  set_names(c("Code", str_c("sd_", names(.[2:5]))))

n_adoption_mean
n_adoption_sd
```

# Length

```{r}
dd %>% 
  filter(!(str_detect(ID, "uc") | str_detect(ID, "qa"))) %>% 
  count(ID, code) %>% 
  group_by(code) %>% 
  summarize(mean_length = mean(n),
            sd_length = sd(n))
```

# N participating at least one

```{r}
one_or_more <- function(x) {
  sum(if_else(x > 0, 1, 0))
}

dd %>% 
  filter(!(str_detect(ID, "uc") | str_detect(ID, "qa"))) %>% 
  count(screen_name, code) %>% 
  spread(code, n, fill = 0) %>% 
  semi_join(i) %>% 
  summarize_if(is.numeric, one_or_more) %>% 
  gather(key, val) %>% 
  mutate(prop = val / 247)
```

# M individuals participated

```{r}
dd %>% 
  filter(!(str_detect(ID, "uc") | str_detect(ID, "qa"))) %>% 
  count(ID, screen_name, code) %>% 
  count(ID, screen_name, code) %>% 
  group_by(ID, code) %>% 
  summarize(sum_n_groups = sum(n)) %>% 
  group_by(code) %>% 
  summarize(mean_n = mean(sum_n_groups),
            sd_n = sd(sum_n_groups))

```

# M groups

```{r}
dd %>% 
  filter(!(str_detect(ID, "uc") | str_detect(ID, "qa"))) %>% 
  count(ID, group, code) %>% 
  count(ID, group, code) %>% 
  group_by(ID, code) %>% 
  summarize(sum_n_groups = sum(n)) %>% 
  group_by(code) %>% 
  summarize(mean_n = mean(sum_n_groups),
            sd_n = sd(sum_n_groups))
```

# M adoption statuses

```{r}
dd %>% 
  filter(!(str_detect(ID, "uc") | str_detect(ID, "qa"))) %>% 
  count(ID, adoption_tri, code) %>% 
  count(ID, adoption_tri, code) %>% 
  group_by(ID, code) %>% 
  summarize(sum_n_groups = sum(n)) %>% 
  group_by(code) %>% 
  summarize(mean_n = mean(sum_n_groups),
            sd_n = sd(sum_n_groups))
```