---
title: "Thread Summary"
author: "JMR"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
params:
  coded_threads: ""
  influence: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE)
coded_threads <- params$coded_threads
influence <- params$influence
```

```{r output}
n_groups <- coded_threads %>% 
  count(ID, group, code) %>% 
  count(ID, group, code) %>% 
  group_by(ID, code) %>% 
  summarize(n_groups = sum(n))

coded_threads %>% 
  count(ID, group, code) %>% 
  count(ID, group, code) %>% 
  spread(group, n, fill = 0) %>% 
  dplyr::select(ID:Teacher) %>% 
  gather(key, val, -ID, -code) %>% 
  group_by(code, key) %>% 
  summarize(mean_val = mean(val)) %>% 
  spread(key, mean_val) %>% 
  ungroup() %>% 
  dplyr::select(Code = code, Teacher, Administrator, Researcher, Organization, Other) %>% 
  filter(Code != "RT")

tm <- coded_threads %>% 
  count(ID, group, code) %>% 
  count(ID, group, code) %>% 
  group_by(ID, code) %>% 
  summarize(sum_n_groups = sum(n))

tm$code <- as.factor(tm$code)
m <- glm(sum_n_groups ~ code, data = tm, family = "poisson")
g <- glht(m, mcp(code="Tukey"))
summary(m)
summary(g)

# length 2 - same res
sum_n_groups <- coded_threads %>% 
  count(ID, status_id, code) %>% 
  count(ID, status_id, code) %>% 
  group_by(ID, code) %>% 
  summarize(sum_n_groups = sum(n))

coded_threads %>% 
  count(ID, status_id, code) %>% 
  count(ID, status_id, code) %>% 
  group_by(ID, code) %>% 
  summarize(sum_n_groups = sum(n)) %>% 
  group_by(code) %>% 
  summarize(mean_n = mean(sum_n_groups),
            sd_n = sd(sum_n_groups))

tm <- coded_threads %>% 
  count(ID, status_id, code) %>% 
  count(ID, status_id, code) %>% 
  group_by(ID, code) %>% 
  summarize(sum_n_groups = sum(n))

tm$code <- as.factor(tm$code)
m <- glm(sum_n_groups ~ code, data = tm, family = "poisson")
g <- glht(m, mcp(code="Tukey"))
summary(m)
summary(g)

# m individuals participated
ind_participated <- coded_threads %>% 
  count(ID, screen_name, code) %>% 
  count(ID, screen_name, code) %>% 
  group_by(ID, code) %>% 
  summarize(ind_participated = sum(n))

coded_threads %>% 
  count(ID, screen_name, code) %>% 
  count(ID, screen_name, code) %>% 
  group_by(ID, code) %>% 
  summarize(sum_n_groups = sum(n)) %>% 
  group_by(code) %>% 
  summarize(mean_n = mean(sum_n_groups),
            sd_n = sd(sum_n_groups))

tm <- coded_threads %>% 
  count(ID, screen_name, code) %>% 
  count(ID, screen_name, code) %>% 
  group_by(ID, code) %>% 
  summarize(sum_n_groups = sum(n))

tm$code <- as.factor(tm$code)
m <- glm(sum_n_groups ~ code, data = tm, family = "poisson")
g <- glht(m, mcp(code="Tukey"))
summary(m)
summary(g)

# m groups participated
n_groups <- coded_threads %>% 
  count(ID, group, code) %>% 
  count(ID, group, code) %>% 
  group_by(ID, code) %>% 
  summarize(n_groups = sum(n))

coded_threads %>% 
  count(ID, group, code) %>% 
  count(ID, group, code) %>% 
  group_by(ID, code) %>% 
  summarize(sum_n_groups = sum(n)) %>% 
  group_by(code) %>% 
  summarize(mean_n = mean(sum_n_groups),
            sd_n = sd(sum_n_groups))

tm <- coded_threads %>% 
  count(ID, group, code) %>% 
  count(ID, group, code) %>% 
  group_by(ID, code) %>% 
  summarize(sum_n_groups = sum(n))

tm$code <- as.factor(tm$code)
m <- glm(sum_n_groups ~ code, data = tm, family = "poisson")
g <- glht(m, mcp(code="Tukey"))
summary(m)
summary(g)

# n adoption statuses
n_adoption <-
  coded_threads %>% 
  count(ID, adoption_tri, code) %>% 
  count(ID, adoption_tri, code) %>% 
  group_by(ID, code) %>% 
  summarize(n_adoption = sum(n))

coded_threads %>% 
  count(ID, adoption_tri, code) %>% 
  count(ID, adoption_tri, code) %>% 
  group_by(ID, code) %>% 
  summarize(sum_n_groups = sum(n)) %>% 
  group_by(code) %>% 
  summarize(mean_n = mean(sum_n_groups),
            sd_n = sd(sum_n_groups))

tm <- coded_threads %>% 
  count(ID, adoption_tri, code) %>% 
  count(ID, adoption_tri, code) %>% 
  group_by(ID, code) %>% 
  summarize(sum_n_groups = sum(n))

tm$code <- as.factor(tm$code)
m <- glm(sum_n_groups ~ code, data = tm, family = "poisson")
g <- glht(m, mcp(code="Tukey"))
summary(m)
summary(g)

# n individuals participated in at least one
one_or_more <- function(x) {
  sum(if_else(x > 0, 1, 0))
}

coded_threads %>% 
  count(screen_name, code) %>% 
  spread(code, n, fill = 0) %>% 
  semi_join(influence) %>% 
  summarize_if(is.numeric, one_or_more) %>% 
  gather(key, val) %>% 
  mutate(prop = val / 247)

tm <- coded_threads %>% 
  count(screen_name, code) %>% 
  spread(code, n, fill = 0) %>% 
  semi_join(influence) %>% 
  summarize_if(is.numeric, one_or_more) %>% 
  gather(key, val)

cst <- chisq.test(tm$val)
cst
tm
cst$stdres
```